const defaultTheme = require("tailwindcss/defaultTheme")

module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#8dadff",
          50: "#edf4ff",
          100: "#deecff",
          200: "#c4dbff",
          300: "#a0c3ff",
          400: "#8dadff",
          500: "#5b7cf9",
          600: "#3d54ee",
          700: "#2f41d3",
          800: "#2939aa",
          900: "#293886",
          950: "#181e4e",
        },
        grid: {
          purple: {
            50: "#f0f4ff",
            100: "#e1e5ff",
            200: "#c8cffe",
            300: "#a6affc",
            400: "#8387f6",
            500: "#6b67ef",
            600: "#5949e4",
            700: "#4935d0",
            800: "#3a2ea3",
            900: "#342b82",
            950: "#211c4a",
          },
          green: {
            50: "#ebfff4",
            100: "#ccffe3",
            200: "#9dfbcc",
            300: "#7cf4c0",
            400: "#29e097",
            500: "#17b078",
            600: "#12875e",
            700: "#12684d",
            800: "#14523e",
            900: "#133f33",
            950: "#0c221d",
          },
          teal: {
            50: "#f4fafa",
            100: "#d5eff0",
            200: "#a7e5e6",
            300: "#6cd3da",
            400: "#2fc2d0",
            500: "#1cb4c4",
            600: "#0d8496",
            700: "#086d7d",
            800: "#045e6c",
            900: "#03535e",
            950: "#012a32",
          },
        },
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            "--tw-prose-body": theme("colors.slate[200]"),
            "--tw-prose-headings": theme("colors.slate[50]"),
            "--tw-prose-lead": theme("colors.slate[400]"),
            "--tw-prose-links": theme("colors.slate[50]"),
            "--tw-prose-bold": theme("colors.slate[50]"),
            "--tw-prose-counters": theme("colors.slate[400]"),
            "--tw-prose-bullets": theme("colors.slate[600]"),
            "--tw-prose-hr": theme("colors.slate[700]"),
            "--tw-prose-quotes": theme("colors.slate[100]"),
            "--tw-prose-quote-borders": theme("colors.slate[700]"),
            "--tw-prose-captions": theme("colors.slate[400]"),
            "--tw-prose-code": theme("colors.slate[200]"),
            "--tw-prose-pre-code": theme("colors.slate[200]"),
            "--tw-prose-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-th-borders": theme("colors.slate[600]"),
            "--tw-prose-td-borders": theme("colors.slate[700]"),
            "blockquote p:first-of-type::before": null,
            "blockquote p:last-of-type::after": null,
            "code::before": null,
            "code::after": null,
            code: {
              backgroundColor: "var(--tw-prose-pre-bg)",
              fontSize: "87.5%",
              fontWeight: "500",
              borderRadius: "3px",
              padding: "0.125em",
            },
          },
        },
      }),
    },
    fontFamily: {
      sans: ['"Karla"', ...defaultTheme.fontFamily.sans],
      mono: ['"IBM Plex Mono"', ...defaultTheme.fontFamily.mono],
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/line-clamp"),
  ],
}
